name: HelloWorld
# when to trigger this pipeline. We can trigger on push or manual or someother events like creating PR, updating PR, creating branches, creating issues
on: [push] #triggers
jobs: # pipeline. one workflow can have multiple pipelines
  job_name:
    runs_on: ubuntu-latest #Linux OS. We can have windows or Mac
    steps: #stages
      - name: step1
        run: echo "HelloWorld"
      - name: step2
        run: echo "Viva La Vida" #long live life