name: conditions
on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: github.ref == 'refs/heads/feature-**'
        run: echo "Hello World"
      - name: step 2
        if: github.ref == 'refs/heads/main'
        run: echo "Hello Github Actions"