name: Parallel
on: [push]
jobs: 
  #job1 and job4 will run parallely. Since No dependency on them
  job-1:  #job_name should be unique
    runs-on: ubuntu-latest
    steps:
    - name: step 1
      run: Hello "I'm from job-1"

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
    - name: step 2
      run: Hello "I'm from job-2"

  job-3:
    runs-on: ubuntu-latest
    needs: job-2
    steps:
    - name: step 3
      run: Hello "I'm from job-3"

  job-4:  #job_name should be unique
    runs-on: ubuntu-latest
    steps:
    - name: step 4
      run: Hello "I'm from job-4"
