name: Parallel
on: [push]
jobs: 
  job-1:
    runs-on: ubuntu-latest
    steps:
    - name: step 1
      run: Hello "I'm from job-1"

  job-2:
  runs-on: ubuntu-latest
  steps:
  - name: step 2
    run: Hello "I'm from job-2"

  job-3:
  runs-on: ubuntu-latest
  steps:
  - name: step 3
    run: Hello "I'm from job-3"
